### ISSUE TITLE
TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by makusu2005** [JWardee/wp-sniffer#1]
Hi!

This repo sounds like exactly what I need, I just can't seem to get it to work. This is the error when running 'python3 wp_sniffer'

Traceback (most recent call last):
  File "wp_sniffer", line 9, in <module>
    print(ScanManager().run_all(url))
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/wp_sniffer/scan_manager.py", line 12, in run_all
    db_manager.update_db()
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/wp_sniffer/db_manager.py", line 7, in update_db
    if not csv_list_exists():
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/wp_sniffer/db_manager.py", line 12, in csv_list_exists
    return os.path.exists(os.path.dirname(os.path.realpath(__file__)) + os.getenv("CSV_PLUGIN_LIST_DIR"))

What can I do to fix this?

**Comment by makusu2005** [comment]
my bad, set the .env file in the wrong directory.
